sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: "eHskDysfryQqAzPHUZ+Xd+GYrvQgyL3cD78M8Hx0jpYajPdOpRdUnAN0DijgD5PqYkJrykUI5du4GzeMH2ibFKVK77L5WSKRjmYWEWuoFrcH8BJyf9g3D1mI3CeKvUUNbtQJAMhTvfS2icTqX/qab6jbXtU+EMhZMOXpx8/W/RRJBrLGPqO6eU9qpbdwROXGda+roFrgXxfBPquJEtqFIgSAtLnV3K386QsEwqrxUYbWZkVVFZ14DGTXpIpL9lVs/rtbaZaTmfDHQIBmqYwwGFrymKcl2AInB5ZUNXbWu41oTeWxidhs8dvns39nmINGP/fdmaxyCO8c13zi9IWMG2WUbDZASFuASilmhce+8L7uajz+9RSearwz+gbDpFn9rzPpCFaIbzjRbkb24pnyVtxjJorFKgJWNFluvsQUOxAkCdMnE2VD5SlfUmvfvfe37VjIhMF7yEHxQFRYPJAq78pgKES/jRNWHuw6zu2hjX8bHpel1zdHhCUWKtj4+KZjT+BUbbQ+iHc3Lpt8MJG6lLOe7iXM21mK3yIkdBzWM5voiuiggQbrp9Gz0OgDGhtd5aOBnTRHkG1ckG8PFudYt7ZkD/RPgs1aMgoAeQKgt8NPTAid16eBkc6Jcf6M9NZBGnkdsFCk/K6hdybz1+5XbG7C3cRTyeGAJQ5w5snsyP8="
branches:
  only:
  - master
