sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: lTRps5vuFt0Hufrb7U6gGaDph9pjf/ZJlPn5A/cObTtV1NnQAF81omcpnwwooDSF6Nbjc1H69N7oUm8KZD0Sf1rATNl06lYCD1WLI2GlJQSGWSq9vJQ5FhpD8T3FYRZJwXopvoLfTqD/+rf5EL79z+Q8ORw9lvF317/7eDHmwwhFFLGLl6CmvirJIyFvC29wRylJsqw2zHCvA82SV/IrkLLK4ml7XDmqzqam6IFI9x0DgAMRjQ+WSDLohMkF37mnJovFWifGnboHBT13WmGdLHiMzUoMTZB7RtslY7Xm3vnwtLEbBVax74T2YAvkWSIHF3/McER2wFUxEitSIeMRkx4vlD6KpqQH7TKj0Jpf57amNa7ZrVyeAnXDhL36QjH3rZnNUs73g10BHfgyEleAifOf+YGPOivzNUedNlLNDWJ8ebWzVz35TSMI5T7InqDFCi69l6KeTRnl/NqJV3Qjf1eBLVkqVpMGNan5BWcry1qQno3XHyYVrVaDb+LAzz3NAOlyCgSzGJyIWDAGg6izFOAgZXnIyKjWnVTvDCfzT0C55kvsnveQCS/9pdTCUv/NmbeJaoOTUUivang0x63IXWovFu9FdMv67K2jMLLQPmVMPH0AiFWyg/HT+u28EF0K9b1azYjWVOAnusvwBfPmLdkKiEKRz4ekxVXIOTdEkAI=
branches:
  only:
  - master
